// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-2",
  aws_cognito_identity_pool_id:
    "ap-southeast-2:d953cb9a-b56a-4b2c-81fa-76a5e8aa086b",
  aws_cognito_region: "ap-southeast-2",
  aws_user_pools_id: "ap-southeast-2_E5oXXELo0",
  aws_user_pools_web_client_id: "4isahps56aud9h4jpuo1l6rik6",
  oauth: {},
  API: {
    endpoints: [
      {
        name: "quizAPI",
        endpoint: `https://de7u5nxssg.execute-api.ap-southeast-2.amazonaws.com/${env}`
      }
    ]
  }
};

export default awsmobile;
