// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:6c41eb3b-6284-4b18-85f0-22d655c292ed",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_WmVaJUIcM",
    "aws_user_pools_web_client_id": "789nl5q3ig8arfkejvh0mde4es",
    "oauth": {},
    "API": {
        "endpoints": [
            {
                "name": "quizAPI",
                "endpoint": "https://de7u5nxssg.execute-api.ap-southeast-2.amazonaws.com/prod"
            }
        ]
    }
};


export default awsmobile;
